
# Site settings
title: The ANCHOR - Your gateway into our documentation
description: Test documentation site

# Build settings
theme: jekyll-theme-leap-day
remote-theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme 
show_downloads: false
